from pathlib import Path
import re

# Extend the pure DNA contract so an upstream deterministic producer decision can
# be recorded without forcing the DNA module to consume engine RNG itself.
core_path = Path("src/core/song-dna.js")
core = core_path.read_text()
old_signature = '''  swing = 0,
  melodicRange = 10,
  phraseBars = 4,
} = {}) {'''
new_signature = '''  swing = 0,
  melodicRange = 10,
  melodicDirection = null,
  phraseBars = 4,
} = {}) {'''
if core.count(old_signature) != 1:
    raise RuntimeError(f"Song DNA signature anchor count={core.count(old_signature)}")
core = core.replace(old_signature, new_signature, 1)
old_direction = '''  const direction = sourceDNA?.melodic?.direction
    ?? (domainSeed(identitySeed, "melodic-direction") % 2 === 0 ? 1 : -1);'''
new_direction = '''  const direction = sourceDNA?.melodic?.direction
    ?? ([1, -1].includes(melodicDirection)
      ? melodicDirection
      : (domainSeed(identitySeed, "melodic-direction") % 2 === 0 ? 1 : -1));'''
if core.count(old_direction) != 1:
    raise RuntimeError(f"Song DNA direction anchor count={core.count(old_direction)}")
core = core.replace(old_direction, new_direction, 1)
core_path.write_text(core)

# The integration patch initially constructs DNA immediately after narrative
# selection. Move that construction to the exact location where the legacy
# blueprint consumed its melodic-direction RNG draw. This preserves all
# downstream candidate RNG sequencing and therefore existing novelty behavior.
engine_path = Path("src/music-engine.js")
source = engine_path.read_text()
early_pattern = re.compile(
    r'  const songDNA = createDeterministicSongDNA\(\{[\s\S]*?\n  \}\);\n'
    r'(?=  const hookCandidates = structure\.filter)'
)
source, count = early_pattern.subn('', source, count=1)
if count != 1:
    raise RuntimeError(f"early Song DNA block removal count={count}")

old_direction_line = '''  const direction = songDNA.melodic.direction;
  const sectionPlans = structure.map((section, index) => {'''
new_direction_block = '''  const dnaMelodicDirection = rng.bool(0.58) ? 1 : -1;
  const songDNA = createDeterministicSongDNA({
    genre: config.genre,
    bpm: config.tempo,
    key: config.key,
    scale: config.scale,
    seed: config.seed,
    narrativeId: narrative.id,
    styleAnchor: {
      drumGroove: style.drumGroove,
      bassGroove: style.bassGroove,
      chordMotion: style.chordMotion,
      melodyShape: style.melodyShape,
    },
    structure,
    sourceDNA: source?.songDNA ?? null,
    syncopation: config.syncopation,
    swing: config.swing,
    melodicRange: config.melodicRange,
    melodicDirection: dnaMelodicDirection,
    phraseBars: clamp(
      Math.round(finite(style.rhythmIdentity?.phraseCycle, GENRE_PROFILES[config.genre].arrangement.phraseBars)),
      2,
      8,
    ),
  });
  const direction = songDNA.melodic.direction;
  const sectionPlans = structure.map((section, index) => {'''
if source.count(old_direction_line) != 1:
    raise RuntimeError(f"blueprint direction anchor count={source.count(old_direction_line)}")
source = source.replace(old_direction_line, new_direction_block, 1)
engine_path.write_text(source)

# Lock the override behavior in the dedicated pure-contract test generated by
# the main integration patcher.
test_path = Path("tests/song-dna.test.mjs")
tests = test_path.read_text()
anchor = '''test("Song DNA splits deterministic domain seeds and section memories", () => {'''
insert = '''test("Song DNA records an upstream deterministic melodic direction", () => {
  const ascending = createSongDNA({ ...BASE, melodicDirection: 1 });
  const descending = createSongDNA({ ...BASE, melodicDirection: -1 });
  assert.equal(ascending.melodic.direction, 1);
  assert.equal(descending.melodic.direction, -1);
  assert.equal(createSongDNA({ ...BASE, melodicDirection: -1 }).melodic.direction, -1);
});

'''
if tests.count(anchor) != 1:
    raise RuntimeError(f"Song DNA direction test anchor count={tests.count(anchor)}")
tests = tests.replace(anchor, insert + anchor, 1)
test_path.write_text(tests)

print("Preserved the legacy blueprint RNG sequence while recording direction in Song DNA.")
